os : osx
osx_image: xcode10
language: swift
script: xcodebuild clean build test -project Shefuda.xcodeproj -scheme "Shefuda" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.0,name=iPhone X" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
xcode_project: Shefuda.xcodeproj
xcode_scheme: Shefuda