//
//  SoundClipData.swift
//  Shefuda
//
//  Created by Shawon Ashraf on 8/3/18.
//  Copyright © 2018 Shawon Ashraf. All rights reserved.
//

import Foundation

class SoundClipData {
    // MARK: sounds dictionary
    // sound file names without extension
    static let soundClips: [String: String] = [
        "আগুণ নিয়ে খেলবিনা":"agon_niye_khelbina",
        "এই ছেলে তোর গার্লফ্রেন্ড নেই?": "ai_sele_tor_girlfriend_nei",
        "এখন গালি দিবো":"akhon_gali_dibo",
        "এখন কি মদ খাওয়ার সময়?": "akhon_ki_mod_khawar_somoy",
        "আমার একটা টেলিফোনে":"amar_akta_telifone_prithibi_kape",
        "আমার মত হতে চাও?":"amar_moto_hote_chaw",
        "আমার নিউ বান্ধবী":"amar_new_bandhobi",
        "আমার অগণিত বান্ধবী": "amar_ogonito_bandhobi",
        "আমার ভয় মানুষে": "amar_voy_manosh_e",
        "আমি এই দেশ স্বাধীন করসি": "ami_ai_desh_sadhin_korsi",
        "আমি বিশ্বের সেরা গোয়েন্দা": "ami_bishsher_sera_goyenda",
        "আমি একজন VIP": "ami_ekjon_vip",
        "আমি এসেছি ঘুম ভাঙাতে": "ami_eshesi_ghum_vangate",
        "আমি ফকির দরবেশ": "ami_fokir_dorbesh",
        "আমি হবো বঙ্গপিতা": "ami_hobo_bongovita",
        "আমি মৃত্যুকে জয় করেছি": "ami_mrittoke_joy_koresi",
        "আমি ভাষার আবিষ্কারক": "ami_vashar_abishsek",
        "আমি ভয় পাই না": "ami_voy_paina_ami_nirvik",
        "আমাকে কোটি মানুষ": "amke_koti_koti_manush",
        "আমাকে ভালোবাসেন কেন?": "amke_valobasen_kenu",
        "আমার একটা ফসম": "amr_akta_foshom_chirte_parbina",
        "আমার অনেক জীবনী": "amr_onk_jiboni_prokash_hoyese",
        "আমার পেট কত বড়": "amr_pet_koto_boro",
        "আমার একটাই দূর্বলতা": "amr_sodho_ektai_dorbolota",
        "আপনারা ঘুম থেকে": "apnara_ghom_theke",
        "আপনারা প্রতিবাদ করুন": "apnara_protibad_koron",
        "B A L বাল": "b_a_l_bal",
        "বান্দরের কি লেজ আছে?": "bandorer_ki_lej_ase",
        "বাংলার মানুষ এক হউ": "banglar_manosh_ak_hou",
        "বাঁশ দেই": "bash_dei",
        "বেঈমানি করেছে": "beimani_korese",
        "বেত দিয়ে মারতে": "bet_diye_marte",
        "বিশ্ববিখ্যাত": "bishshobikhhato",
        "ভণ্ডামি করতেসো?": "bondami_korteaso",
        "চাপাবাজি করো না?": "chapabazi_koro_na",
        "চিয়ার্স": "cheers",
        "চুলকানি তল্কানি": "chulkani_tolkani_to_thakei",
        "ডাইনী রাক্ষসী": "daini_rakhkhoshi",
        "ডাকাতের সর্দার ক্রিমিনাল": "dakat_er_sordar_criminal_joghonno_beyadob",
        "ধন্যবাদ": "dhonnobad",
        "ডোনাল্ড ট্রাম্পকে ২ বার": "donald_trump_ke_2ba_president",
        "ফেসবুকে এসে সত্যি বলি": "facebook_ese_sotto_boli",
        "ফালতু কোথাকার যত্তসব": "faltu_kothakar_jottosob",
        "ফুটবল খেলবা আমার সাথে?": "football_khelba_amr_sathe",
        "গালে টস টস করে": "gal_toshtosh_kore",
        "গায়ের রং ফর্সা আছে": "gayer_rong_forsha_ase",
        "ঘুম ভাঙ্গানিয়া পাখি": "ghum_vanganiya_pakhi",
        "গোলাম এর বাচ্চা": "golam_er_bachcha",
        "গলাভাঙা": "golavanga",
        "গরীইইইব!": "gorib",
        "হারামজাদারা": "haramjadara",
        "হারামজাদী": "haramjadi",
        "হাজার সাংবাদিক আমার ইন্টার্ভিউ নেয়": "hazar_sangbadik_amar_interview_nei",
        "হাজার টা আইডি বানাবো": "hazar_ta_id_banabo",
        "হ্যালো!": "helloo",
        "হিংসা সং": "hingsa_song",
        "হিংসে হয় ?": "hingse_hoi",
        "হুঁশ আছে?": "hosh_ase",
        "ইতিহাস জানোস?": "itihash_janos",
        "জামা কাপড় না পড়লে": "jama_kapor_na_porle",
        "জাতিসংঘের উপদেষ্টা ছিলাম": "jatisongher_upodeshta_silam",
        "যেমন কুকুর তেমন মুগুর": "jmn_kokor_tmn_mogor",
        "জুতার বাড়ির চোটে দাঁত": "jotar_barir_chote_dat",
        "কানে ঢুকেনা?": "kane_dhukena",
        "কেমন লাগছে তোদের?": "kemon_lagse_toder",
        "খেলা দেখ": "khela_dekh",
        "কী খবর তোমাদের?": "ki_khobor_tromader",
        "কপালটা দেখেছো আমার": "kopal_ta_dekheyso_kmn_amar",
        "কথা কিন্তু সত্য": "kotha_kinto_sotto",
        "কথা সত্য": "kotha_sotoo",
        "লাথি মারলে কে শব্দ করেনা?": "lathi_marle_ke_sobdo_korena",
        "লেজ বিশিষ্ট ছিলাম": "lej_bishisto_silam",
        "লাভ ইউ": "love_you",
        "মাল": "mal",
        "মারতে মারতে দাঁতগুলো": "marte_marte_dat_gulo_fele_dite_parle",
        "মেয়েটি খুব সুন্দর": "meyeti_khube_sundor",
        "মিয়া বিবি রাজি": "miya_bibi_raji",
        "মদ বেশি খাইয়া ফালাইসি": "mod_beshi_khaya_falaysi",
        "মদ বিনিময় করসি": "mod_binimoy_korsi",
        "মদ খা": "mod_kha",
        "মদ খাবা নাকি?": "mod_khaba_naki",
        "মদ খাইতেসি এখন": "mod_khaitasi_akhon",
        "মজা করি না": "moja_kori_na",
        "ন্যাংটা হইয়া দেখাইয়া দিমু": "nangta_hoya_dekhaya_dimo",
        "নিজের টাকা দিয়া মদ কিনসি": "nijer_taka_diya_mod_kinsi",
        "নোয়াখাইল্লা খাটাশ": "noakhailla_khatash",
        "অফ কোর্স আমি ইয়াং": "of_course_ami_young",
        "ঐযে কাউয়া": "oije_kauua",
        "ঐশ্বরিয়া আমাকে চুমু": "oishoria_rai_amk_chomo",
        "ওকে সুস্থ করে দিবো": "oke_sostho_kore_dibo",
        "উল্টা পাল্টা": "olta_palta_boltesi_kenu",
        "অনেক আকাম করো তোমরা": "onk_akam_kooro_tomra",
        "ওরে বাদ দে": "ore_bad_de",
        "অসাধারণ গরু": "osadharon_goro",
        "অশিক্ষিত মুরুক্ষ বস্তি": "oshikhkhito_morkhobo_bosti",
        "পাদ দিলে হাগো": "pad_dile_hago",
        "প্যান্ট খোলো": "pant_kholo",
        "পিসলা পানি বাইর": "pisla_pani_bair",
        "প্রেম ধর্ম": "prem_dhormo",
        "প্রেমে স্যাকা": "preme_seka",
        "প্রিয়তমা তোমাকে ভালোবাসি": "priyotoma_tomake_valobashi",
        "প্রমাণ আছে?": "proman_ase",
        "সাইকোলজিক্যাল ট্রিটমেন্ট": "psylogical_treatment",
        "রাত জাগা পাখি": "rat_jaga_pakhira",
        "সেজন্য আমি দুঃখিত": "sejonno_ami_ottonto_dokhkhito",
        "স্মার্টফোন দিয়া পরকীয়া": "smartphn_diya_porokiya",
        "সব নোয়াখাইল্লা হয়ে গেসে": "sob_noyakhailla_hoya_gese",
        "সবাই ভালো থাকেন": "sobai_valo_thakben_sostho_thakben",
        "সকল প্রাণী সুখী হোক": "sokol_prani_sokhi_hok",
        "সত্য জানতে চাইলে মদ": "sotto_kotha_jante_chaile_mod",
        "টাকা এবং সুন্দরী তরুণী": "taka_abong_sundori_toroni",
        "টাকা পয়সা": "taka_poysa",
        "তাকে ছেড়া স্যান্ডেল নিক্ষেপ করো": "take_sera_sandle_nikhkhep_koro",
        "তার টেলিফোন নাম্বার": "tar_telifon_number_amke_dao",
        "টের পান না?": "ter_pan_na",
        "থ্যাংক ইউ": "thank_you",
        "তোদের মতন শ্রমিক না": "toder_moto_sromik_na",
        "তোমাদের যাদের বান্ধবী নাই": "tomader_jader_bandhobi_nai",
        "তোমাদের কি কষ্ট লাগে না?": "tomader_ki_kosto_lagena",
        "তোমাদের লজ্জা শরম নাই?": "tomader_lozza_sorom_nai",
        "তোমাকে দেখে রাজপুত্র": "tomake_dekhe_rajpotro",
        "তোমরা তো পশুর চেয়ে অধম": "tomra_to_oshor_cheye",
        "তোর মুখে গাইয়ে গন্ধ": "tor_mokhe_gondho_gaye_gondho",
        "তোর পতন হবে": "tor_poton_hobe",
        "তোরা মানুষ": "tora_manosh",
        "ট্রস ট্রস করে মারা": "tros_tros_kore_mara",
        "তুই গরীব": "tui_gorib",
        "তুই রাজাকার": "tui_razakar",
        "ভালো মানুষ": "valo_manosh",
        "তর পুটকি তুই মার":"TOR PUTKI TUI MAR",
        "তোর সোনা খাঁড়ায় না":"tor shona toh kharay na",
        "লাভ ইস লাইফ":"love is life",
        "খানকির পোলা পেত্নী সুদাস":"khankir pola petni sudas",
        "বেশ্যা পোলা":"beshsha pola",
        "তরা মইরা যা":"tora moira ja",
        "খেলারে সুদি":"khelare sudi",
        "লজ্জা লজ্জা লজ্জা":"lojja lojja lojja",
        "আমার বাল ফালা":"amar bal fala",
        "ফকিন্নি গরিব":"FOKINNI GORIB",
        "অশিক্ষিত বর্বর ছোটলোকের জাতেরা":"oshikhito borbor chotoloker jatera",
        "বেশ্যার সোঁদারা":"beshar sodara",
        "আই হেইট ইউ":"I hate you",
        "মুরুক্ষসোঁদা":"murukkhusuda",
        "এই তরা মরে যা":"ei tora more ja",
        "ফকিন্নির সোঁদা দেশ":"fokinnir suda desh",
        "তোর বইনরে তুই সোঁদ":"TOR BOINRE TUI SOD",
        "লাভ নেভার ডাইস":"love never dies",
        "মাদারফাকার":"motherfucker",
        "শয়তান":"shoitan",
        "আমারে কুত্তায় সোঁদাইসে":"amare kuttay sudaise",
        "ধর্ম সোঁদা":"dhormo soda",
        "তর মায়েরে সুদি":"tor mayere sudi",
        "সুদি না":"sudi na",
        "হা হা হা হা":"Evil Laugh",
        "মদ খাবি মানুষ হবি":"mod khabi manush hobi",
        "তর মায়েরে তুই সোদ":"tor mayere tui sod",
        "খানকির পোলা ১":"khankir pola 01",
        "ওকে থুতু মারো":"oke thutu maro",
        "মদ খাবি, মাগী সুদবি, ওকে?":"mod khabi, magi sudbi, ok",
        "তোরা কুত্তাসোদা":"tora kuttasoda",
        "তোরা মুরুক্ষসোদা":"tora murukkhusuda",
        "কুত্তা দিয়া সোদাবো":"kutta diye sodabo",
        "গভর্নরের পুটকিতে আমি ছেপ দিয়া":"governor er putkite ami sep dia dhukai disi",
        "তর মা বুড়ি সুদি":"TOR MA BURI SUDI",
        "তোর মায়ের ভোঁদা রে আমি সুদি না":"tor maayer bhoda re ami sudi na",
        "তোর মায়েরে সুদতে আসি নাই":"TOR MAIRE SUDTE ASHI NAI KHANKIR POLA",
        "খুবই অসভ্য খারাপ":"khubi oshobho kharap",
        "শুভ সন্ধ্যা":"shubho shondha",
        "রাবিশ":"rubbish",
        "তোর মায়ের ভোঁদা দিয়া":"tor maayer bhoda dia dhukai dimu tor mukh dia bair hoibo",
        "মদ খাবি মাগি সুদবি":"mod khabi, magi sudbi",
        "মদ না খাইলে তোর মায়েরে সুদি":"mod na khaile tor mayere sudi",
        "তরা সব চোর":"Tora shob chor",
        "তড় মায়েরে তুই ২":"tor mayere tui sod 02",
        "শুভ অপরাহ্ণ":"shubho oporanho",
        "বেশ্যা মাগী":"beshsha magi",
        "ইউ ব্লাডই বাস্টার্ড":"YOU BLOODY BASTARD",
        "মদ খাও আর মাগী চোদো":"mod khao ar magi chudo",
        "নির্লজ্জ বেহায়া":"nirlojjo behaya",
        "কুত্তার বাচ্চা":"KUTTAR BACHA",
        "এসেন্ডেড খানকির পোলা":"Ascended khankir pola",
        "খানকি মাগী":"khanki magi",
        "মদ খাবি নাকি":"mod khabi naki",
        "স্টুপিড":"stupid",
        "মিথ্যুক ধোঁকাবাজ":"mithuk dhokabaj",
        "গুষ্টি সুদি":"gushti sudi",
        "শুটকি খাস, পেত্নী সোদস":"shutki khas, petni sudos",
        "সুপ্রভাত বাংলাদেশে এখন সুপ্রভাত":"Shuprobhat Bangladeshe Ekhon Shuprobhat",
        "বেশ্যার সোঁদা":"beshar soda",
        "খানকি":"khanki",
        "মদ খাবো আর মাগী সুদবো":"mod khabo ar magi sudbo",
        "মাদারফাকার বাস্টার্ড জারজ":"MOTHERFUCKER BASTARD JAROZ",
        "তোদের আমি ঘৃণা করি":"toder ami ghrina kori",
        "কুত্তা দিয়া সোদাইতে সোদাইতে":"kutta diya sodaite sodaite",
        "তগরে আমি কুত্তা দিয়া চোদাই":"togore ami kutta diya chodai",
        "মাগী সুদো":"magi sudo",
        "তার পুটকি মাইরা দিসি":"taar putki maira disi",
        "গরীবের সোঁদা":"goriber suda",
        "খানকির পোলা মদ খাঁ":"khankir pola mod kha",
        "তুই গরীব সোঁদা":"tui gorib suda",
        "ভোঁদা দিয়া কুত্তা দিয়া সোদাই":"bhoda diya kutta diya sodai"
    ]
    
    // MARK: file extension for sounds
    static let fileExtension: String = ".mp3"
}
